import {
  Dumbbell,
  Briefcase,
  Book,
  Code2,
  Brain,
  Footprints,
  Activity,
  Bed,
  ShoppingCart,
  Coffee,
  Soup,
  UtensilsCrossed,
  ShowerHead,
  PartyPopper,
  Phone,
  Tv,
  Music,
  Car,
  Plane,
  NotebookPen,
} from "lucide-react";

export const activityOptions = [
  { label: "Gym", icon: Dumbbell },
  { label: "Work", icon: Briefcase },
  { label: "Reading", icon: Book },
  { label: "Coding", icon: Code2 },
  { label: "Meditation", icon: Brain },
  { label: "Walk", icon: Footprints },
  { label: "Yoga", icon: Activity },
  { label: "Sleep", icon: Bed },
  { label: "Groceries", icon: ShoppingCart },
  { label: "Coffee", icon: Coffee },
  { label: "Breakfast", icon: Soup },
  { label: "Lunch", icon: UtensilsCrossed },
  { label: "Dinner", icon: UtensilsCrossed },
  { label: "Shower", icon: ShowerHead },
  { label: "Party", icon: PartyPopper },
  { label: "Call", icon: Phone },
  { label: "TV", icon: Tv },
  { label: "Music", icon: Music },
  { label: "Drive", icon: Car },
  { label: "Travel", icon: Plane },
  { label: "Journaling", icon: NotebookPen },
];
